<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>text.log</string>

		<key>fileTypes</key>
		<array>
			<string>log</string>
		</array>

		<key>name</key>
		<string>Log file</string>

		<key>patterns</key>
		<array>



			<!--<dict>
				<key>match</key>
				<string>\[(INFO|NOTICE)\]</string>

				<key>name</key>
				<string>markup.inserted log.info</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\[WARNING\]</string>

				<key>name</key>
				<string>markup.deleted log.warning</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\[(ERROR|CRITICAL)\]</string>

				<key>name</key>
				<string>string.regexp, strong log.error</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b\d{4}-\d{2}-\d{2}(T|\b)</string>

				<key>name</key>
				<string>comment log.date</string>
			</dict>

			<dict>
				<key>match</key>
				<string>(?<=(^|\s))\d{2}[^\w\s]\d{2}[^\w\s]\d{4}\b</string>

				<key>name</key>
				<string>comment log.date</string>
			</dict>


			<dict>
				<key>match</key>
				<string>\b[0-9a-fA-F]{8}[-]?([0-9a-fA-F]{4}[-]?){3}[0-9a-fA-F]{12}\b</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>

			<dict>
				<key>match</key>
				<string>sofia\/[a-zA-Z]+\/[a-zA-Z]</string>
				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>
			<dict>
				<key>match</key>
				<string>"[^"]*"</string>

				<key>name</key>
				<string>string log.string</string>
			</dict>

			<dict>
				<key>match</key>
				<string>(?<![\w])'[^']*'</string>

				<key>name</key>
				<string>string log.string</string>
			</dict>

			<dict>
				<key>match</key>
				<string>\b[a-z]+://\S+\b/?</string>

				<key>name</key>
				<string>constant.language log.constant</string>
			</dict>-->
		</array>

		<key>uuid</key>
		<string>E81BB6AB-CAC7-4C27-9A79-4137A4693EBD</string>
	</dict>
</plist>
